name: cacao_scan
description: Aplicación mínima para login y detección de moniliasis en cacao.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  crypto: ^3.0.3
  http: ^1.6.0
  image: ^4.1.7
  image_picker: ^1.0.7
  path: ^1.8.3
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  sqflite: ^2.3.0
  tflite_flutter:
    path: third_party/tflite_flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/brand/cacao_logo.png
    - assets/brand/cacao_mark.png
    - assets/modelo_cacao_monilia_ssd.tflite
    - assets/labels_cacao_monilia_ssd.txt
